version: '3.9'
services:
  atlas:
    container_name: atlas
    build:
      context: .
      dockerfile: ./apps/atlas/Dockerfile
    restart: always
    env_file:
      - .env
    # ports:
    #   - "3002:3000"
    networks:
      - backend

  cerberus:
    container_name: cerberus
    build: 
      context: .
      dockerfile: ./apps/cerberus/Dockerfile
    restart: always
    env_file:
      - .env
    # ports:
    #   - "3001:3000"
    networks:
      - backend

  heimdall:
    container_name: heimdall
    build:
      context: .
      dockerfile: ./apps/heimdall/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    # depends_on:
    #   - cerberus
    #   - atlas
    networks:
      - backend

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: > 
      redis-server 
      --aclfile /usr/local/etc/redis/users.acl 
    env_file:
      - .env
    volumes:
      - 'redis-data:/data_redis'
      - './redis/redis-acl.conf:/usr/local/etc/redis/users.acl' 
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tellme_db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis-data:
    driver: local
  db-data:
    driver: local
