services:
  # Redis cache
  redis:
    image: redis:latest
    container_name: redis 
    command: > 
      redis-server 
      --aclfile /usr/local/etc/redis/users.acl 
    env_file:
      - .env
    volumes:
      - 'redis-data:/data_redis'
      - './redis/redis-acl.conf:/usr/local/etc/redis/users.acl' 
    ports:
      - "6379:6379"
    networks:
      - backend

  # just in dev
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data_redis_insight
    networks:
      - backend

  # Postgres
  postgres:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: tellme_db
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgdmin4
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8080
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  redis-data:
    driver: local
  redis-insight:
    driver: local
  db-data:
    driver: local
  pgadmin-data:
    driver: local